### ISSUE TITLE
Some missing stuff in the nuget packages

### ISSUE THREAD

**Issue by laheller** [ASCOMInitiative/ASCOMLibrary#25] opened 2023-01-04 14:02 UTC
Hi!
@Peter-Simpson 

I just started to evaluate the latest (1.0.52) version of the [nuget packages](https://www.nuget.org/profiles/ASCOM-Initiative) and realised there are some missing classes, which are also part of the [documentation](https://ascom-standards.org/Help/Developer/html/G_ASCOM.htm).

For example following I was not able to find in the nuget packages/assemblies:

- [AstroUtils class](https://ascom-standards.org/Help/Developer/html/T_ASCOM_Astrometry_AstroUtils_AstroUtils.htm)
- [Novas31 class](https://ascom-standards.org/Help/Developer/html/T_ASCOM_Astrometry_NOVAS_NOVAS31.htm)
- [Ephemeris class](https://ascom-standards.org/Help/Developer/html/T_ASCOM_Astrometry_Kepler_Ephemeris.htm)

Do you plan to include these classes in the future version of nuget packages?

BR,

Ladislav

**Comment by Peter-Simpson** [comment] 2023-01-08 17:31
Hi Ladislav,

Your documentation link shows the components available in the ASCOM Platform (Windows only) rather than in the ASCOM Library, whose documentation is here: [ASCOM Library Documentation](https://ascom-standards.org/library/html/3e0a4970-b422-4427-bb1e-789bb79e1b4f.htm). 

We only plan to support SOFA for astronomical calculation in the ASCOM Library because NOVAS is no longer supported by its developers, the US Naval Observatory. The AstroUtils functions, which are not easily reproduced using standard .NET functions, are available in the Library's ASCOM.Tools.Utilities class.

Porting the Ephemeris class, which is part of the NOVASCOM /Kepler packages is not yet scheduled because of the work involved in converting from VB to C#. 

Best wishes, Peter

**Comment by laheller** [comment] 2023-01-09 09:06
Hi! @Peter-Simpson 

Thanks for info.

> The AstroUtils functions, which are not easily reproduced using standard .NET functions, are available in the Library's ASCOM.Tools.Utilities class.

Checked this one again and I see that the platform's [AstroUtils.EventTimes](https://ascom-standards.org/Help/Developer/html/M_ASCOM_Astrometry_AstroUtils_AstroUtils_EventTimes.htm) method is missing from the library's ASCOM.Tools.Utilities class both in the documentation and in the nuget package.

Next, I deployed my test .NET6 console application built as a single deployment file to a new machine **without** ASCOM Platfrom installed and it did not even start. It was not obvious for me that nuget the packages also requires the ASCOM platform installation. Maybe it should be mentioned in the [README](https://github.com/ASCOMInitiative/ASCOMLibrary/blob/master/README.md) file.

BR,

Ladislav

**Comment by Peter-Simpson** [comment] 2023-01-09 09:22
Hi Ladislav,

 

I had to omit EventTimes because it uses the NOVAS 3.1 component that isn’t part of the library. I’ll have a look at whether I can migrate NOVAS to the Library as well, but it is a significant effort to create and test native versions for Apple (Intel and Apple silicon), Intel Linux 64bit , Arm32 and Arm64 architectures. I have already done this for SOFA so at least there is a method to follow!

 

I am surprised that your application didn’t work without the Platform. When you say it didn’t start, what error did it produce? How did you determine that the root cause is a Library issue?

 

Best wishes, Peter

**Comment by laheller** [comment] 2023-01-09 09:55
@Peter-Simpson 

> I am surprised that your application didn’t work without the Platform. When you say it didn’t start, what error did it produce? How did you determine that the root cause is a Library issue?

Only available error I see is a new event log in the Windows Event Viewer with the below details:

> Application: AscomTest2.exe
> CoreCLR Version: 6.0.1122.52304
> .NET Version: 6.0.11
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.TypeInitializationException: The type initializer for 'ASCOM.Com.PlatformUtilities' threw an exception.
>  ---> ASCOM.ValueNotSetException: ComUtilities.IsMinimumRequiredVersion - Unable to read the Platform version number. **Is the ASCOM Platform installed?** See inner exception for details. get - no value has been set.
>  ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at ASCOM.Com.PlatformUtilities..cctor()
>    --- End of inner exception stack trace ---
>    at ASCOM.Com.PlatformUtilities..cctor()
>    --- End of inner exception stack trace ---
>    at ASCOM.Com.PlatformUtilities.get_PlatformVersion()
>    at AscomTest2.Form1..ctor() in C:\Dev\AscomTest2\Form1.cs:line 9
>    at AscomTest2.Program.Main() in C:\Dev\AscomTest2\Program.cs:line 11
> 

BR,

Ladislav

**Comment by Peter-Simpson** [comment] 2023-01-09 09:59
Many thanks, that was a recent addition, and I clearly hadn’t considered the possibility of the Platform not being present. I’ll issue an update; please ignore version 1.0.70, which I released earlier today, it doesn’t have a fix for this issue.

 

Best wishes, Peter

**Comment by laheller** [comment] 2023-01-09 10:17
@Peter-Simpson 

> Many thanks, that was a recent addition, and I clearly hadn’t considered the possibility of the Platform not being present. I’ll issue an update; please ignore version 1.0.70, which I released earlier today, it doesn’t have a fix for this issue. Best wishes, Peter

So if I understand correctly, the Platform is always required, right?

BR,

Ladislav

**Comment by Peter-Simpson** [comment] 2023-01-09 10:55
The only Library component I’m aware of that has a dependency on the Platform is the PlatformUtilities component. Please can you post the code that you are expecting to work, and I’ll check whether that should work but has bugs or whether it will only ever work when the Platform is present.

 

Thanks, Peter

**Comment by Peter-Simpson** [comment] 2023-01-09 14:03
Hi Ladislav,

 

When you run your code on a PC without the ASCOM Platform, the PlatformUtilities.PlatformVersion  method will throw an exception saying that it can’t find the Platform version because the Platform is not installed or is corrupt. This seems reasonable to me because there can’t be a Platform version if the Platform is not installed. 

 

I suggest putting the code in your Form1 initiator inside a try-catch block and then popping up a message box if an exception is thrown. Alternatively, you could just ignore the exception and carry on but it’s likely that the Profile.GetDrivers call will also return an exception.

 

Best wishes, Peter

**Comment by laheller** [comment] 2023-01-09 14:38
@Peter-Simpson 

Yes, the reason is clear. At the end we can say that Platform is (or might be) required for the library.
I would mention that in the README.md of this repository.

BR,

Ladislav

**Comment by Peter-Simpson** [comment] 2023-01-09 22:42
Hi Ladislav.

 

I’ve updated the read-me as suggested: https://github.com/ASCOMInitiative/ASCOMLibrary/blob/master/README.md 

 

Best wishes, Peter

**Comment by Peter-Simpson** [comment] 2024-05-01 15:14
I'm closing this issue as it seems fixed and there has been no activity since January 2023.

**Closed by Peter-Simpson** 2024-05-01 15:14 UTC
